#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Author:  LJ
Email:   admin@attacker.club
Time:    2020/4/9 11:40
Description: 
"""



import  subprocess

subprocess.run(["python", "./manage.py", "runserver", "0.0.0.0:8000"],stderr=subprocess.PIPE,stdout=subprocess.PIPE,check=True)
